services:
  postgres:
    image: postgres:17
    container_name: ankaa_postgres_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ankaa_dev
    ports:
      - "5432:5432" # PostgreSQL exposed on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ankaa_network
  timescale:
    image: timescale/timescaledb-ha:pg17
    container_name: ankaa_timescale_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ankaa_timescale_dev
    ports:
      - "5433:5432" # Map host 5433 to container's 5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - ankaa_network
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -t 'test/topic' -C 1 -E 2>/dev/null || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ankaa_network
  rust_iot_mock:
    build:
      context: ./iot_mock
      dockerfile: Dockerfile
    container_name: rust_iot_mock
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt_broker
      - RUST_LOG=info
    networks:
      - ankaa_network
  phoenix:
    build:
      context: ./ankaa_beacon
      dockerfile: Dockerfile.dev
    container_name: ankaa_phoenix
    depends_on:
      - postgres
      - timescale
      - mqtt
    env_file:
      - ./ankaa_beacon/.env
    environment:
      - MIX_ENV=dev
    ports:
      - "4000:4000"
    networks:
      - ankaa_network
    volumes:
      - ./ankaa_beacon:/app
      - phoenix_deps:/app/deps
      - phoenix_build:/app/_build

networks:
  ankaa_network:
    driver: bridge

volumes:
  postgres_data:
  timescale_data:
  mosquitto_data:
  mosquitto_logs:
  phoenix_deps:
  phoenix_build:
