version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ankaa_postgres_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ankaa_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./postgres-certs:/var/lib/postgresql/certs
    networks:
      - ankaa_network
    # command: >
    #   -c ssl=on
    #   -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
    #   -c ssl_key_file=/var/lib/postgresql/certs/server.key
  redis:
    image: redis:7-alpine
    container_name: ankaa_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ankaa_network

  timescale:
    image: timescale/timescaledb-ha:pg17
    container_name: ankaa_timescale_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ankaa_timescale_dev
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      # - ./timescale-certs:/var/lib/postgresql/certs
    networks:
      - ankaa_network
    # command: >
    #   -c ssl=on
    #   -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
    #   -c ssl_key_file=/var/lib/postgresql/certs/server.key

networks:
  ankaa_network:
    driver: bridge

volumes:
  postgres_data:
  timescale_data:
