services:
  postgres:
    image: postgres:17
    container_name: ankaa_postgres_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ankaa_dev
    ports:
      - "5432:5432" # PostgreSQL exposed on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ankaa_network
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -t 'test/topic' -C 1 -E 2>/dev/null || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ankaa_network
  rust_iot_mock:
    build:
      context: ./iot_mock
      dockerfile: Dockerfile
    container_name: rust_iot_mock
    depends_on:
      mqtt:
        condition: service_healthy
    environment:
      - MQTT_HOST=mqtt_broker
      - RUST_LOG=info
    networks:
      - ankaa_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  inbucket:
    image: inbucket/inbucket
    container_name: inbucket
    ports:
      - "9000:9000" # Web UI
      - "2500:2500" # SMTP Port
    networks:
      - ankaa_network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  ankaa_network:
    driver: bridge

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  phoenix_deps:
  phoenix_build:
