FROM hexpm/elixir:1.18.3-erlang-27.3.3-debian-bullseye-20250407-slim

# Install build dependencies
RUN apt-get update -y && apt-get install -y \
    build-essential \
    gcc \
    make \
    git \
    inotify-tools \
    curl \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set development environment
ENV MIX_ENV=dev

# Copy mix files
COPY mix.exs mix.lock ./
COPY config config

# Get dependencies and compile them in the container
RUN mix deps.get && mix deps.compile

EXPOSE 4000

CMD ["sh", "-c", "cd assets && npm install && cd .. && mix ecto.migrate && mix phx.server"]