import Config

# Configure your database
config :ankaa, Ankaa.Repo,
  username: System.get_env("POSTGRES_USER", "user"),
  password: System.get_env("POSTGRES_PASSWORD", "password"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  database: System.get_env("POSTGRES_DB", "ankaa_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POSTGRES_POOL_SIZE", "10"))

# TimescaleDB config
config :ankaa, Ankaa.TimescaleRepo,
  migration_primary_key: [name: :id, type: :binary_id],
  migration_source: "timescale_schema_migrations",
  database: System.get_env("TIMESCALE_DB", "ankaa_timescale_dev"),
  username: System.get_env("TIMESCALE_USER", "user"),
  password: System.get_env("TIMESCALE_PASSWORD", "password"),
  hostname: System.get_env("TIMESCALE_HOST", "localhost"),
  port: String.to_integer(System.get_env("TIMESCALE_PORT", "5433")),
  pool_size: String.to_integer(System.get_env("TIMESCALE_POOL_SIZE", "10")),
  migrations_path: "priv/timescale_repo/migrations"

# MQTT Configuration
config :ankaa, :mqtt,
  host: System.get_env("MQTT_HOST", "localhost"),
  port: String.to_integer(System.get_env("MQTT_PORT", "1883")),
  username: System.get_env("MQTT_USERNAME"),
  password: System.get_env("MQTT_PASSWORD")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :ankaa, AnkaaWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT", "4000"))],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env(
      "SECRET_KEY_BASE",
      "3v+8HkjX7xIsfOa7UR02eyboYnxi5TiEunfhZc7pk9NfWOfxVl4K0hr1J/XkIIcA"
    ),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ankaa, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ankaa, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ankaa, AnkaaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ankaa_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ankaa, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ankaa_beacon, AnkaaBeaconWeb.Endpoint,
  watchers: [
    node: [
      "node_modules/esbuild/bin/esbuild",
      "--watch",
      "--sourcemap=inline",
      "--bundle",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]
