import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ankaa, AnkaaWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ankaa.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :ankaa, :env, :prod

config :ankaa, :start_mqtt_consumer, true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# # Configure your primary PostgreSQL database
# config :ankaa, Ankaa.Repo,
#   username: System.get_env("POSTGRES_USER"),
#   password: System.get_env("POSTGRES_PASSWORD"),
#   hostname: System.get_env("POSTGRES_HOST"),
#   # Updated to match .env
#   database: System.get_env("POSTGRES_DB"),
#   port: String.to_integer(System.get_env("POSTGRES_PORT") || "5432"),
#   ssl: true

# # Configure your MQTT broker
config :ankaa, :mqtt,
  host: System.get_env("MQTT_HOST"),
  port: String.to_integer(System.get_env("MQTT_PORT") || "8883"),
  username: System.get_env("MQTT_USERNAME"),
  password: System.get_env("MQTT_PASSWORD"),
  enable_ssl: true,
  ssl_options: [
    verify: :verify_peer,
    CAfile: System.get_env("MQTT_CA_CERT"),
    cert: System.get_env("MQTT_CLIENT_CERT"),
    key: System.get_env("MQTT_CLIENT_KEY"),
    server_name_indication: System.get_env("MQTT_HOST"),
    tls_versions: [:"tlsv1.2", :"tlsv1.3"],
    server_name_indication: System.get_env("MQTT_HOST")
  ]
